### ISSUE TITLE
프밍 스터디 수정 사항 및 요청 사항

### ISSUE THREAD

**Issue by hbin12212** [winterlood/udemy-devstu-study-withme#24]
### 이슈 내용
- 프밍 스터디 수정 사항 및 요청 사항

### 상세 내용
1. 수정사항 (꼭 수정해야 하는 기능)

- [x]  스터디 포스트 > 포스트 페이지의 수정 시간 부분 삭제 요청
![image](https://user-images.githubusercontent.com/52522662/163918431-84b41d79-3bb5-427e-b68d-73e505e7785a.png)

- [x]  프밍 스터디 사이트 모바일 버전 -> 글자가 한 글자 씩 밀리는 현상 수정 요청
![image](https://user-images.githubusercontent.com/52522662/163918538-681baaa2-bc53-44bf-96f0-132554477dc5.png)
![image](https://user-images.githubusercontent.com/52522662/163918639-28daea1b-3467-49da-aa45-6b39a3771044.png)

2. 요청 사항 (개선했으면 좋겠는 기능)

- [ ]  스터디 전체 보기 페이지 에서 ( 참여 가능한, 모집 마감된, 전체 ) 필터 적용 후 스터디 조회 시, 뒤로가기를 눌렀을 때 필터 적용 풀림 현상 

- [x]  프밍스터디 홈 에서 신청 가능한 스터디가 없으면, 비어 보이는 부분 때문에  "현재 진행 중인 스터디" 혹은 "마감된 스터디" 컴포넌트 추가 요청

**Comment by winterlood** [comment]
스터디 전체 보기 페이지 에서 ( 참여 가능한, 모집 마감된, 전체 ) 필터 적용 후 스터디 조회 시, 뒤로가기를 눌렀을 때 필터 적용 풀림 현상은 의도된 동작 방식입니다.

필터의 상태를 url query를 이용하지 않고, state를 이용하여 저장하기 때문에 그렇습니다.
